//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EntityFramework_Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
